{
  parserClass="cruelteam.plugins.mnlang.parser.MnlangParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Mnlang"
  psiImplClassSuffix="Impl"
  psiPackage="cruelteam.plugins.mnlang.psi"
  psiImplPackage="cruelteam.plugins.mnlang.psi.impl"

  elementTypeHolderClass="cruelteam.plugins.mnlang.psi.MnlangTypes"
  elementTypeClass="cruelteam.plugins.mnlang.psi.MnlangElementType"
  tokenTypeClass="cruelteam.plugins.mnlang.psi.MnlangTokenType"

  psiImplUtilClass="cruelteam.plugins.mnlang.psi.impl.MnlangPsiImplUtil"
}

//simpleFile ::= item_*
//private item_ ::= (property|COMMENT|CRLF)
//property ::= (KEY? SEPARATOR VALUE?) | KEY {methods=[getKey getValue]}

file ::= line*
line ::= entry | PREFIX | COMMENT
entry ::= (KEY? SEPARATOR VALUE?) | KEY